//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Services {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EMailTexte {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EMailTexte() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Services.EMailTexte", typeof(EMailTexte).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///
        ///Wir wünschen Ihnen einen erfolgreichen Tag!
        ///
        ///Ihr Team der Vernetzungsstelle für Schulverpflegung Niedersachsen ähnelt.
        /// </summary>
        internal static string Abschluss {
            get {
                return ResourceManager.GetString("Abschluss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///
        ///
        ///
        ///Sie haben noch Fragen oder Anregungen? Bitte antworten Sie nicht direkt auf diese E-Mail - aus technischen Gründen können wir Ihre Anfrage leider nicht bearbeiten, wenn Sie die Reply-Funktion Ihres E-Mail-Programms wählen.
        ///
        ///Nutzen Sie einfach die Kontaktmöglichkeiten unter:
        ///
        /// ähnelt.
        /// </summary>
        internal static string Anregung {
            get {
                return ResourceManager.GetString("Anregung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sehr geehrter Nutzer,
        ///
        ///Ihr Nutzerkonto für die Caterer Datenbank wurde gerade durch unseren Mitarbeiter eingerichtet. 
        ///Bitte nutzen Sie den mitgesendeten Link zur Vergabe eines Passwortes und zum Abschluss Ihrer Registrierung. 
        ///Im Anschluss steht Ihnen der interne Bereich der Caterer Datenbank zur Verfügung.
        ///Vielen Dank für Ihr Vertrauen. 
        ///
        /// ähnelt.
        /// </summary>
        internal static string Catererangelegt {
            get {
                return ResourceManager.GetString("Catererangelegt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sehr geehrter Nutzer, 
        ///
        ///Sie haben ein Benutzerkonto bei der Caterer Datenbank der Vernetzungsstelle Schulverpflegung Niedersachsenangelegt. Eine gute Entscheidung! Nur so können Sie bei der Empfehlung von Verpflegungsanbietern für Schulen berücksichtigt werden.
        ///
        ///Damit Sie Ihr Konto nutzen können, fehlt nur noch ein Schritt:
        ///Bestätigen Sie Ihre E-Mail Adresse. 
        ///Klicken Sie dafür einfach auf den nach folgenden Link. 
        ///
        /// ähnelt.
        /// </summary>
        internal static string CatererRegistrierung1 {
            get {
                return ResourceManager.GetString("CatererRegistrierung1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///
        ///Im Anschluss können Sie mit Ihren Anmeldedaten alle Funktionen des internen Bereichs nutzen. ähnelt.
        /// </summary>
        internal static string CatererRegistrierung2 {
            get {
                return ResourceManager.GetString("CatererRegistrierung2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sehr geehrter Mitarbeiter, 
        ///
        ///Ihr Nutzerkonto für die Caterer Datenbank wurde gerade durch den Administrator eingerichtet. 
        ///Bitte nutzen Sie den mitgesendeten Link zur Vergabe eines Passwortes und zum Abschluss Ihrer Registrierung. 
        ///
        /// ähnelt.
        /// </summary>
        internal static string Mitarbeiterangelegt {
            get {
                return ResourceManager.GetString("Mitarbeiterangelegt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sehr geehrter Nutzer,
        ///
        ///in der Caterer Datenbank wurden neue Fragen in Ihrem Fragebogen veröffentlicht. 
        ///
        ///Bitte nehmen Sie sich ein paar Minuten Zeit und aktualisieren Sie Ihre Antworten bzw. ergänzen Sie diese. 
        ///
        /// ähnelt.
        /// </summary>
        internal static string NeueFragen {
            get {
                return ResourceManager.GetString("NeueFragen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sehr geehrter Nutzer,
        ///
        ///wie von Ihnen gewünscht, wurde Ihr Nutzerkonto der Caterer Datenbank von unseren Mitarbeitern aktualisiert. 
        ///Vielen Dank für Ihr Vertrauen. 
        ///
        ///Für Rückfragen stehen wir Ihnen gerne zur Verfügung.  ähnelt.
        /// </summary>
        internal static string NutzerÄnderung {
            get {
                return ResourceManager.GetString("NutzerÄnderung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sehr geehrter Nutzer,
        ///
        ///Ihr Nutzerkonto wurde gerade aus der Caterer Datenbank entfernt. 
        ///Wir bedauern, dass Sie nicht weiter in unserer Caterer Datenbank geführt werden möchten.  ähnelt.
        /// </summary>
        internal static string Nutzerlöschen {
            get {
                return ResourceManager.GetString("Nutzerlöschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sehr geehrter Nutzer,
        ///
        ///falls Sie Ihr Passwort vergessen haben, können Sie sich mit Hilfe des folgenden Links ein neues Passwort vergeben. 
        ///Bitte beachten Sie, dass der Link nur 2 Stunden gültig ist.Danach müssen Sie eine neue E-Mail anfordern.
        ///
        /// ähnelt.
        /// </summary>
        internal static string PWvergessen {
            get {
                return ResourceManager.GetString("PWvergessen", resourceCulture);
            }
        }
    }
}
