//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caterer_DB.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Caterer_DB.Resources.LoginResources", typeof(LoginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansprechpartner ähnelt.
        /// </summary>
        public static string Ansprechpartner {
            get {
                return ResourceManager.GetString("Ansprechpartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nutzereintrag nicht vorhanden ähnelt.
        /// </summary>
        public static string BenutzerBeschreibung {
            get {
                return ResourceManager.GetString("BenutzerBeschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User not Exist ähnelt.
        /// </summary>
        public static string BenutzerCode {
            get {
                return ResourceManager.GetString("BenutzerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie einen Benutzernamen ein ähnelt.
        /// </summary>
        public static string BenutzerValidationMessage {
            get {
                return ResourceManager.GetString("BenutzerValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzer konnte nicht aus Datenbank gelesen werden ähnelt.
        /// </summary>
        public static string DatenbankBeschreibung {
            get {
                return ResourceManager.GetString("DatenbankBeschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Error ähnelt.
        /// </summary>
        public static string DatenbankCode {
            get {
                return ResourceManager.GetString("DatenbankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail ist bereits registriert ähnelt.
        /// </summary>
        public static string EMailVorhanden {
            get {
                return ResourceManager.GetString("EMailVorhanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail oder Passwort falsch ähnelt.
        /// </summary>
        public static string PasswortBeschreibung {
            get {
                return ResourceManager.GetString("PasswortBeschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falsche Passwort ähnelt.
        /// </summary>
        public static string PasswortCode {
            get {
                return ResourceManager.GetString("PasswortCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie ein Passwort ein ähnelt.
        /// </summary>
        public static string PasswortValidationMessage {
            get {
                return ResourceManager.GetString("PasswortValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort vergessen? ähnelt.
        /// </summary>
        public static string PasswortVergessen {
            get {
                return ResourceManager.GetString("PasswortVergessen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mit der Datenbank möchten wir Caterer und Schulen zusammenbringen und eine flächendeckende Versorgung der Schulen mit einer guten Schulverpflegung unterstützen. 
        ///Daher freuen wir uns besonders, wenn Sie als Caterer für die Schulverpflegung Ihr Angebot darstellen, aktualisieren und bereit sind, dass wir Ihre Daten im Bedarfsfall an Schulen oder auch Schulträger weiterleiten dürfen. Ob Warmverpflegung oder Cook&amp;Chill, ob deutschlandweite oder regionale kleine Lieferkreise, für kleine und große Schüleranzahle [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string StartseiteText {
            get {
                return ResourceManager.GetString("StartseiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Herzlich Willkommen auf der Seite der Caterer-Datenbank der Vernetzungsstelle Schulverpflegung Niedersachsen ähnelt.
        /// </summary>
        public static string StartseiteTextÜberschrift {
            get {
                return ResourceManager.GetString("StartseiteTextÜberschrift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail oder Passwort falsch ähnelt.
        /// </summary>
        public static string UnbekannterBeschreibung {
            get {
                return ResourceManager.GetString("UnbekannterBeschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UnknownError ähnelt.
        /// </summary>
        public static string UnbekannterCode {
            get {
                return ResourceManager.GetString("UnbekannterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Platzhalter ähnelt.
        /// </summary>
        public static string WillkommensText {
            get {
                return ResourceManager.GetString("WillkommensText", resourceCulture);
            }
        }
    }
}
