//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EMailTexte {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EMailTexte() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.EMailTexte", typeof(EMailTexte).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Wir wünschen Ihnen einen erfolgreichen Tag!
        ///
        ///Ihr Team der Vernetzungsstelle für Schulverpflegung Niedersachsen.
        /// </summary>
        internal static string Abschluss {
            get {
                return ResourceManager.GetString("Abschluss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///Sie haben noch Fragen oder Anregungen? Bitte antworten Sie nicht direkt auf diese E-Mail - aus technischen Gründen können wir Ihre Anfrage leider nicht bearbeiten, wenn Sie die Reply-Funktion Ihres E-Mail-Programms wählen.
        ///
        ///Nutzen Sie einfach die Kontaktmöglichkeiten unter:
        ///
        ///.
        /// </summary>
        internal static string Anregung {
            get {
                return ResourceManager.GetString("Anregung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sehr geehrter Nutzer,
        ///
        ///Ihr Nutzerkonto für die Caterer Datenbank wurde gerade durch unseren Mitarbeiter eingerichtet. 
        ///Bitte nutzen Sie den mitgesendeten Link zur Vergabe eines Passwortes und zum Abschluss Ihrer Registrierung. 
        ///Im Anschluss steht Ihnen der interne Bereich der Caterer Datenbank zur Verfügung.
        ///Vielen Dank für Ihr Vertrauen. 
        ///
        ///.
        /// </summary>
        internal static string Catererangelegt {
            get {
                return ResourceManager.GetString("Catererangelegt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sehr geehrter Nutzer, 
        ///
        ///Sie haben ein Benutzerkonto bei der Caterer Datenbank der Vernetzungsstelle Schulverpflegung Niedersachsenangelegt. Eine gute Entscheidung! Nur so können Sie bei der Empfehlung von Verpflegungsanbietern für Schulen berücksichtigt werden.
        ///
        ///Damit Sie Ihr Konto nutzen können, fehlt nur noch ein Schritt:
        ///Bestätigen Sie Ihre E-Mail Adresse. 
        ///Klicken Sie dafür einfach auf den nach folgenden Link. 
        ///
        ///.
        /// </summary>
        internal static string CatererRegistrierung1 {
            get {
                return ResourceManager.GetString("CatererRegistrierung1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Im Anschluss können Sie mit Ihren Anmeldedaten alle Funktionen des internen Bereichs nutzen..
        /// </summary>
        internal static string CatererRegistrierung2 {
            get {
                return ResourceManager.GetString("CatererRegistrierung2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sehr geehrter Mitarbeiter, 
        ///
        ///Ihr Nutzerkonto für die Caterer Datenbank wurde gerade durch den Administrator eingerichtet. 
        ///Bitte nutzen Sie den mitgesendeten Link zur Vergabe eines Passwortes und zum Abschluss Ihrer Registrierung. 
        ///
        ///.
        /// </summary>
        internal static string Mitarbeiterangelegt {
            get {
                return ResourceManager.GetString("Mitarbeiterangelegt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sehr geehrter Nutzer,
        ///
        ///in der Caterer Datenbank wurden neue Fragen in Ihrem Fragebogen veröffentlicht. 
        ///
        ///Bitte nehmen Sie sich ein paar Minuten Zeit und aktualisieren Sie Ihre Antworten bzw. ergänzen Sie diese. 
        ///
        ///.
        /// </summary>
        internal static string NeueFragen {
            get {
                return ResourceManager.GetString("NeueFragen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sehr geehrter Nutzer,
        ///
        ///wie von Ihnen gewünscht, wurde Ihr Nutzerkonto der Caterer Datenbank von unseren Mitarbeitern aktualisiert. 
        ///Vielen Dank für Ihr Vertrauen. 
        ///
        ///Für Rückfragen stehen wir Ihnen gerne zur Verfügung. .
        /// </summary>
        internal static string NutzerÄnderung {
            get {
                return ResourceManager.GetString("NutzerÄnderung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sehr geehrter Nutzer,
        ///
        ///Ihr Nutzerkonto wurde gerade aus der Caterer Datenbank entfernt. 
        ///Wir bedauern, dass Sie nicht weiter in unserer Caterer Datenbank geführt werden möchten. .
        /// </summary>
        internal static string Nutzerlöschen {
            get {
                return ResourceManager.GetString("Nutzerlöschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sehr geehrter Nutzer,
        ///
        ///falls Sie Ihr Passwort vergessen haben, können Sie sich mit Hilfe des folgenden Links ein neues Passwort vergeben. 
        ///Bitte beachten Sie, dass der Link nur 2 Stunden gültig ist.Danach müssen Sie eine neue E-Mail anfordern.
        ///
        ///.
        /// </summary>
        internal static string PWvergessen {
            get {
                return ResourceManager.GetString("PWvergessen", resourceCulture);
            }
        }
    }
}
