//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.LoginResources", typeof(LoginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansprechpartner.
        /// </summary>
        public static string Ansprechpartner {
            get {
                return ResourceManager.GetString("Ansprechpartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzereintrag nicht vorhanden.
        /// </summary>
        public static string BenutzerBeschreibung {
            get {
                return ResourceManager.GetString("BenutzerBeschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not Exist.
        /// </summary>
        public static string BenutzerCode {
            get {
                return ResourceManager.GetString("BenutzerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie einen Benutzernamen ein.
        /// </summary>
        public static string BenutzerValidationMessage {
            get {
                return ResourceManager.GetString("BenutzerValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer konnte nicht aus Datenbank gelesen werden.
        /// </summary>
        public static string DatenbankBeschreibung {
            get {
                return ResourceManager.GetString("DatenbankBeschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Error.
        /// </summary>
        public static string DatenbankCode {
            get {
                return ResourceManager.GetString("DatenbankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail ist bereits registriert.
        /// </summary>
        public static string EMailVorhanden {
            get {
                return ResourceManager.GetString("EMailVorhanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail oder Passwort falsch.
        /// </summary>
        public static string PasswortBeschreibung {
            get {
                return ResourceManager.GetString("PasswortBeschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsche Passwort.
        /// </summary>
        public static string PasswortCode {
            get {
                return ResourceManager.GetString("PasswortCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie ein Passwort ein.
        /// </summary>
        public static string PasswortValidationMessage {
            get {
                return ResourceManager.GetString("PasswortValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort vergessen?.
        /// </summary>
        public static string PasswortVergessen {
            get {
                return ResourceManager.GetString("PasswortVergessen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit der Datenbank möchten wir Caterer und Schulen zusammenbringen und eine flächendeckende Versorgung der Schulen mit einer guten Schulverpflegung unterstützen. 
        ///Daher freuen wir uns besonders, wenn Sie als Caterer für die Schulverpflegung Ihr Angebot darstellen, aktualisieren und bereit sind, dass wir Ihre Daten im Bedarfsfall an Schulen oder auch Schulträger weiterleiten dürfen. Ob Warmverpflegung oder Cook&amp;Chill, ob deutschlandweite oder regionale kleine Lieferkreise, für kleine und große Schüleranzahle [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StartseiteText {
            get {
                return ResourceManager.GetString("StartseiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzlich Willkommen auf der Seite der Caterer-Datenbank der Vernetzungsstelle Schulverpflegung Niedersachsen.
        /// </summary>
        public static string StartseiteTextÜberschrift {
            get {
                return ResourceManager.GetString("StartseiteTextÜberschrift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail oder Passwort falsch.
        /// </summary>
        public static string UnbekannterBeschreibung {
            get {
                return ResourceManager.GetString("UnbekannterBeschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnknownError.
        /// </summary>
        public static string UnbekannterCode {
            get {
                return ResourceManager.GetString("UnbekannterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platzhalter.
        /// </summary>
        public static string WillkommensText {
            get {
                return ResourceManager.GetString("WillkommensText", resourceCulture);
            }
        }
    }
}
