//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumTests.Services {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Fehlermeldung {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fehlermeldung() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumTests.Services.Fehlermeldung", typeof(Fehlermeldung).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie müssen die AGBs akzeptieren ähnelt.
        /// </summary>
        internal static string AGB_Zustimmung {
            get {
                return ResourceManager.GetString("AGB_Zustimmung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Anrede&quot; ist erforderlich. ähnelt.
        /// </summary>
        internal static string Anrede_Erforderlich {
            get {
                return ResourceManager.GetString("Anrede_Erforderlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Funktion des Ansprechpartners&quot; ist erforderlich. ähnelt.
        /// </summary>
        internal static string Ansprechpartner_Erforderlich {
            get {
                return ResourceManager.GetString("Ansprechpartner_Erforderlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenschutzbestimmungen müssen zugestimmt werden ähnelt.
        /// </summary>
        internal static string Datenschutzbestimmungen_Zustimmung {
            get {
                return ResourceManager.GetString("Datenschutzbestimmungen_Zustimmung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail ist bereits registriert ähnelt.
        /// </summary>
        internal static string Email_Bereits_Vorhanden {
            get {
                return ResourceManager.GetString("Email_Bereits_Vorhanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;E-Mail&quot; ist erforderlich. ähnelt.
        /// </summary>
        internal static string Email_Erforderlich {
            get {
                return ResourceManager.GetString("Email_Erforderlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld E-Mail enthält keine gültige E-Mail-Adresse. ähnelt.
        /// </summary>
        internal static string Email_Ungültig {
            get {
                return ResourceManager.GetString("Email_Ungültig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Firmenname&quot; ist erforderlich. ähnelt.
        /// </summary>
        internal static string Firma_Erforderlich {
            get {
                return ResourceManager.GetString("Firma_Erforderlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Lieferumkreis&quot; ist erforderlich. ähnelt.
        /// </summary>
        internal static string Lieferumkreis_Erforderlich {
            get {
                return ResourceManager.GetString("Lieferumkreis_Erforderlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail oder Passwort falsch ähnelt.
        /// </summary>
        internal static string LoginSeite_Email_PW_Fehler {
            get {
                return ResourceManager.GetString("LoginSeite_Email_PW_Fehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Nachname&quot; ist erforderlich. ähnelt.
        /// </summary>
        internal static string Nachname_Erforderlich {
            get {
                return ResourceManager.GetString("Nachname_Erforderlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Organisationsform&quot; ist erforderlich. ähnelt.
        /// </summary>
        internal static string Organisation_Erforderlich {
            get {
                return ResourceManager.GetString("Organisation_Erforderlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Ort&quot; ist erforderlich. ähnelt.
        /// </summary>
        internal static string Ort_Erforderlich {
            get {
                return ResourceManager.GetString("Ort_Erforderlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Postleitzahl&quot; ist erforderlich. ähnelt.
        /// </summary>
        internal static string PLZ_Erforderlich {
            get {
                return ResourceManager.GetString("PLZ_Erforderlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Passwort&quot; ist erforderlich. ähnelt.
        /// </summary>
        internal static string PW_Erforderlich {
            get {
                return ResourceManager.GetString("PW_Erforderlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Passwort Wiederholung&quot; ist erforderlich. ähnelt.
        /// </summary>
        internal static string PW_Wiederholung_Erforderlich {
            get {
                return ResourceManager.GetString("PW_Wiederholung_Erforderlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Straße und Hausnummer&quot; ist erforderlich. ähnelt.
        /// </summary>
        internal static string Straße_Hausnummer_Erforderlich {
            get {
                return ResourceManager.GetString("Straße_Hausnummer_Erforderlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Telefon&quot; ist erforderlich. ähnelt.
        /// </summary>
        internal static string Telefon_Erforderlich {
            get {
                return ResourceManager.GetString("Telefon_Erforderlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Vorname&quot; ist erforderlich. ähnelt.
        /// </summary>
        internal static string Vorname_Erforderlich {
            get {
                return ResourceManager.GetString("Vorname_Erforderlich", resourceCulture);
            }
        }
    }
}
