//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumTests.Services {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hinweise {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hinweise() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumTests.Services.Hinweise", typeof(Hinweise).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihr Account wurde erfolgreich gelöscht! ähnelt.
        /// </summary>
        internal static string Account_Gelöscht {
            get {
                return ResourceManager.GetString("Account_Gelöscht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemeine Geschäftsbedingungen ähnelt.
        /// </summary>
        internal static string AGBseite {
            get {
                return ResourceManager.GetString("AGBseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caterer bearbeiten ähnelt.
        /// </summary>
        internal static string Caterer_Bearbeiten_Seite {
            get {
                return ResourceManager.GetString("Caterer_Bearbeiten_Seite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detailansicht AllYouCanEat GmbH ähnelt.
        /// </summary>
        internal static string Caterer_Details_Seite {
            get {
                return ResourceManager.GetString("Caterer_Details_Seite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caterer hinzufügen ähnelt.
        /// </summary>
        internal static string Caterer_Hinzufügen_Seite {
            get {
                return ResourceManager.GetString("Caterer_Hinzufügen_Seite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caterer ähnelt.
        /// </summary>
        internal static string Catererseite {
            get {
                return ResourceManager.GetString("Catererseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenschutzbestimmungen ähnelt.
        /// </summary>
        internal static string Datenschutzseite {
            get {
                return ResourceManager.GetString("Datenschutzseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigene Daten ähnelt.
        /// </summary>
        internal static string Eigene_Datenseite_Caterer {
            get {
                return ResourceManager.GetString("Eigene_Datenseite_Caterer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigene Daten ähnelt.
        /// </summary>
        internal static string Eigene_Datenseite_Mitarbeiter {
            get {
                return ResourceManager.GetString("Eigene_Datenseite_Mitarbeiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detailansicht Fragen ähnelt.
        /// </summary>
        internal static string Fragen_Details {
            get {
                return ResourceManager.GetString("Fragen_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Frage hinzufügen ähnelt.
        /// </summary>
        internal static string Fragen_Hinzufügen {
            get {
                return ResourceManager.GetString("Fragen_Hinzufügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorie bearbeiten ähnelt.
        /// </summary>
        internal static string Fragen_Kategorie_Bearbeiten {
            get {
                return ResourceManager.GetString("Fragen_Kategorie_Bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorie hinzufügen ähnelt.
        /// </summary>
        internal static string Fragen_Kategorie_Hinzufügen {
            get {
                return ResourceManager.GetString("Fragen_Kategorie_Hinzufügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorien ähnelt.
        /// </summary>
        internal static string Fragen_Kategorie_Übersicht {
            get {
                return ResourceManager.GetString("Fragen_Kategorie_Übersicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Frage bearbeiten ähnelt.
        /// </summary>
        internal static string Fragen_Neu_Bearbeiten {
            get {
                return ResourceManager.GetString("Fragen_Neu_Bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Fragen ähnelt.
        /// </summary>
        internal static string Fragen_Übersicht_Neu {
            get {
                return ResourceManager.GetString("Fragen_Übersicht_Neu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichte Fragen ähnelt.
        /// </summary>
        internal static string Fragen_Übersicht_Öffentlich {
            get {
                return ResourceManager.GetString("Fragen_Übersicht_Öffentlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detailansicht Veröffentlichte Frage ähnelt.
        /// </summary>
        internal static string Fragen_Veröffentlicht_Details {
            get {
                return ResourceManager.GetString("Fragen_Veröffentlicht_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Impressum ähnelt.
        /// </summary>
        internal static string Impressumseite {
            get {
                return ResourceManager.GetString("Impressumseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansprechpartner ähnelt.
        /// </summary>
        internal static string Kontaktseite {
            get {
                return ResourceManager.GetString("Kontaktseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen bestätigen ähnelt.
        /// </summary>
        internal static string Löschen_Bestätigen {
            get {
                return ResourceManager.GetString("Löschen_Bestätigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mitarbeiter bearbeiten ähnelt.
        /// </summary>
        internal static string Mitarbeiter_Bearbeiten {
            get {
                return ResourceManager.GetString("Mitarbeiter_Bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detailansicht Mitarbeiter ähnelt.
        /// </summary>
        internal static string Mitarbeiter_Details {
            get {
                return ResourceManager.GetString("Mitarbeiter_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mitarbeiter hinzufügen ähnelt.
        /// </summary>
        internal static string Mitarbeiter_Hinzufügen {
            get {
                return ResourceManager.GetString("Mitarbeiter_Hinzufügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mitarbeiter ähnelt.
        /// </summary>
        internal static string Mitarbeiter_Seite {
            get {
                return ResourceManager.GetString("Mitarbeiter_Seite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Passwort ähnelt.
        /// </summary>
        internal static string PW_Ändern_Seite {
            get {
                return ResourceManager.GetString("PW_Ändern_Seite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestätigung der Passwortänderung ähnelt.
        /// </summary>
        internal static string PW_Änderung_Bestätigung {
            get {
                return ResourceManager.GetString("PW_Änderung_Bestätigung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihr Passwort wurde erfolgreich geändert! ähnelt.
        /// </summary>
        internal static string PW_Änderung_Erfolgreich {
            get {
                return ResourceManager.GetString("PW_Änderung_Erfolgreich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrierung noch nicht abgeschlossen ähnelt.
        /// </summary>
        internal static string Reg_Email_Verifikation_Fehlt {
            get {
                return ResourceManager.GetString("Reg_Email_Verifikation_Fehlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrierung ähnelt.
        /// </summary>
        internal static string Registrierungsseite {
            get {
                return ResourceManager.GetString("Registrierungsseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startseite - My ASP.NET Application ähnelt.
        /// </summary>
        internal static string Startseite {
            get {
                return ResourceManager.GetString("Startseite", resourceCulture);
            }
        }
    }
}
