//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumTests.Services {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hinweise {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hinweise() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumTests.Services.Hinweise", typeof(Hinweise).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihr Account wurde erfolgreich gelöscht! ähnelt.
        /// </summary>
        internal static string Account_Gelöscht {
            get {
                return ResourceManager.GetString("Account_Gelöscht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen bestätigen ähnelt.
        /// </summary>
        internal static string Account_Löschen_Bestätigen {
            get {
                return ResourceManager.GetString("Account_Löschen_Bestätigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemeine Geschäftsbedingungen ähnelt.
        /// </summary>
        internal static string AGBseite {
            get {
                return ResourceManager.GetString("AGBseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenschutzbestimmungen ähnelt.
        /// </summary>
        internal static string Datenschutzseite {
            get {
                return ResourceManager.GetString("Datenschutzseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigene Daten ähnelt.
        /// </summary>
        internal static string Eigene_Datenseite {
            get {
                return ResourceManager.GetString("Eigene_Datenseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Impressum ähnelt.
        /// </summary>
        internal static string Impressumseite {
            get {
                return ResourceManager.GetString("Impressumseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansprechpartner ähnelt.
        /// </summary>
        internal static string Kontaktseite {
            get {
                return ResourceManager.GetString("Kontaktseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestätigung der Passwortänderung ähnelt.
        /// </summary>
        internal static string PW_Änderung_Bestätigung {
            get {
                return ResourceManager.GetString("PW_Änderung_Bestätigung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihr Passwort wurde erfolgreich geändert! ähnelt.
        /// </summary>
        internal static string PW_Änderung_Erfolgreich {
            get {
                return ResourceManager.GetString("PW_Änderung_Erfolgreich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrierung noch nicht abgeschlossen ähnelt.
        /// </summary>
        internal static string Reg_Email_Verifikation_Fehlt {
            get {
                return ResourceManager.GetString("Reg_Email_Verifikation_Fehlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrierung ähnelt.
        /// </summary>
        internal static string Registrierungsseite {
            get {
                return ResourceManager.GetString("Registrierungsseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startseite - My ASP.NET Application ähnelt.
        /// </summary>
        internal static string Startseite {
            get {
                return ResourceManager.GetString("Startseite", resourceCulture);
            }
        }
    }
}
