//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumTests.Services {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NutzerDaten {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NutzerDaten() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumTests.Services.NutzerDaten", typeof(NutzerDaten).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sebastian ähnelt.
        /// </summary>
        internal static string Dummy_Daten_Vorname {
            get {
                return ResourceManager.GetString("Dummy_Daten_Vorname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2 ähnelt.
        /// </summary>
        internal static string NutzerDaten_Anrede_Frau {
            get {
                return ResourceManager.GetString("NutzerDaten_Anrede_Frau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 ähnelt.
        /// </summary>
        internal static string NutzerDaten_Anrede_Herr {
            get {
                return ResourceManager.GetString("NutzerDaten_Anrede_Herr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tester ähnelt.
        /// </summary>
        internal static string NutzerDaten_Ansprechpartner {
            get {
                return ResourceManager.GetString("NutzerDaten_Ansprechpartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die projekt10test@gmail.com ähnelt.
        /// </summary>
        internal static string NutzerDaten_Email {
            get {
                return ResourceManager.GetString("NutzerDaten_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Testfirma ähnelt.
        /// </summary>
        internal static string NutzerDaten_Firmenname {
            get {
                return ResourceManager.GetString("NutzerDaten_Firmenname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 ähnelt.
        /// </summary>
        internal static string NutzerDaten_Lieferumkreis {
            get {
                return ResourceManager.GetString("NutzerDaten_Lieferumkreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teste ähnelt.
        /// </summary>
        internal static string NutzerDaten_Name {
            get {
                return ResourceManager.GetString("NutzerDaten_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 ähnelt.
        /// </summary>
        internal static string NutzerDaten_Organisationsform {
            get {
                return ResourceManager.GetString("NutzerDaten_Organisationsform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Testen ähnelt.
        /// </summary>
        internal static string NutzerDaten_Ort {
            get {
                return ResourceManager.GetString("NutzerDaten_Ort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 12345 ähnelt.
        /// </summary>
        internal static string NutzerDaten_PLZ {
            get {
                return ResourceManager.GetString("NutzerDaten_PLZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teststraße 0 ähnelt.
        /// </summary>
        internal static string NutzerDaten_Straße_Nr {
            get {
                return ResourceManager.GetString("NutzerDaten_Straße_Nr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 09876/54321 ähnelt.
        /// </summary>
        internal static string NutzerDaten_Telefon {
            get {
                return ResourceManager.GetString("NutzerDaten_Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test ähnelt.
        /// </summary>
        internal static string NutzerDaten_Vorname {
            get {
                return ResourceManager.GetString("NutzerDaten_Vorname", resourceCulture);
            }
        }
    }
}
