//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumTests.Services {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ObjektIDs_Dropdown {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjektIDs_Dropdown() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumTests.Services.ObjektIDs_Dropdown", typeof(ObjektIDs_Dropdown).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigene Daten ähnelt.
        /// </summary>
        internal static string Dropdown_Eigene_Daten {
            get {
                return ResourceManager.GetString("Dropdown_Eigene_Daten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EinstellungenLink ähnelt.
        /// </summary>
        internal static string Dropdown_Einstellungen {
            get {
                return ResourceManager.GetString("Dropdown_Einstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownKonfigurationLogin ähnelt.
        /// </summary>
        internal static string Dropdown_Konfiguration_Login {
            get {
                return ResourceManager.GetString("Dropdown_Konfiguration_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownLogin ähnelt.
        /// </summary>
        internal static string Dropdown_Login {
            get {
                return ResourceManager.GetString("Dropdown_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausloggen ähnelt.
        /// </summary>
        internal static string Dropdown_Login_Ausloggen {
            get {
                return ResourceManager.GetString("Dropdown_Login_Ausloggen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ändern ähnelt.
        /// </summary>
        internal static string Dropdown_Login_PW_Ändern {
            get {
                return ResourceManager.GetString("Dropdown_Login_PW_Ändern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownLogout ähnelt.
        /// </summary>
        internal static string Dropdown_Logout {
            get {
                return ResourceManager.GetString("Dropdown_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loginLinkhead ähnelt.
        /// </summary>
        internal static string Dropdown_Logout_LoginButton {
            get {
                return ResourceManager.GetString("Dropdown_Logout_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die registerLinkhead ähnelt.
        /// </summary>
        internal static string Dropdown_Logout_RegisterButton {
            get {
                return ResourceManager.GetString("Dropdown_Logout_RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownManageCaterer ähnelt.
        /// </summary>
        internal static string Dropdown_Manage_Caterer {
            get {
                return ResourceManager.GetString("Dropdown_Manage_Caterer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CatererAnzeigen ähnelt.
        /// </summary>
        internal static string Dropdown_Manage_Caterer_Anzeigen {
            get {
                return ResourceManager.GetString("Dropdown_Manage_Caterer_Anzeigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CatererHinzufügen ähnelt.
        /// </summary>
        internal static string Dropdown_Manage_Caterer_Hinzufügen {
            get {
                return ResourceManager.GetString("Dropdown_Manage_Caterer_Hinzufügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownManageFragebogen ähnelt.
        /// </summary>
        internal static string Dropdown_Manage_Fragebogen {
            get {
                return ResourceManager.GetString("Dropdown_Manage_Fragebogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FragenAnzeigen ähnelt.
        /// </summary>
        internal static string Dropdown_Manage_Fragebogen_Anzeigen {
            get {
                return ResourceManager.GetString("Dropdown_Manage_Fragebogen_Anzeigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FragebogenBearbeiten ähnelt.
        /// </summary>
        internal static string Dropdown_Manage_Fragebogen_Bearbeiten {
            get {
                return ResourceManager.GetString("Dropdown_Manage_Fragebogen_Bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FragenHinzufügen ähnelt.
        /// </summary>
        internal static string Dropdown_Manage_Fragen_Hinzufügen {
            get {
                return ResourceManager.GetString("Dropdown_Manage_Fragen_Hinzufügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownServiceLogin ähnelt.
        /// </summary>
        internal static string Dropdown_Service_Login {
            get {
                return ResourceManager.GetString("Dropdown_Service_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownServiceLogout ähnelt.
        /// </summary>
        internal static string Dropdown_Service_Logout {
            get {
                return ResourceManager.GetString("Dropdown_Service_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownAGBLogin ähnelt.
        /// </summary>
        internal static string DropdownAGBLogin {
            get {
                return ResourceManager.GetString("DropdownAGBLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownAGBLogout ähnelt.
        /// </summary>
        internal static string DropdownAGBLogout {
            get {
                return ResourceManager.GetString("DropdownAGBLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownDatenschutzLogin ähnelt.
        /// </summary>
        internal static string DropdownDatenschutzLogin {
            get {
                return ResourceManager.GetString("DropdownDatenschutzLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownDatenschutzLogout ähnelt.
        /// </summary>
        internal static string DropdownDatenschutzLogout {
            get {
                return ResourceManager.GetString("DropdownDatenschutzLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownImpressumLogin ähnelt.
        /// </summary>
        internal static string DropdownImpressumLogin {
            get {
                return ResourceManager.GetString("DropdownImpressumLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownImpressumLogout ähnelt.
        /// </summary>
        internal static string DropdownImpressumLogout {
            get {
                return ResourceManager.GetString("DropdownImpressumLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownKontaktLogin ähnelt.
        /// </summary>
        internal static string DropdownKontaktLogin {
            get {
                return ResourceManager.GetString("DropdownKontaktLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DropdownKontaktLogout ähnelt.
        /// </summary>
        internal static string DropdownKontaktLogout {
            get {
                return ResourceManager.GetString("DropdownKontaktLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MitarbeiterAnzeigen ähnelt.
        /// </summary>
        internal static string DropdownMAAnzeigen {
            get {
                return ResourceManager.GetString("DropdownMAAnzeigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MitarbeiterHinzufügen ähnelt.
        /// </summary>
        internal static string DropdownMAHinzufügen {
            get {
                return ResourceManager.GetString("DropdownMAHinzufügen", resourceCulture);
            }
        }
    }
}
