//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumTests.Services {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ObjektIDs_FragebogenManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjektIDs_FragebogenManagement() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumTests.Services.ObjektIDs_FragebogenManagement", typeof(ObjektIDs_FragebogenManagement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bieten Sie Getränke an? ähnelt.
        /// </summary>
        internal static string Frage_Dummyfrage {
            get {
                return ResourceManager.GetString("Frage_Dummyfrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bezeichnung ähnelt.
        /// </summary>
        internal static string Frage_Formulieren_Textbox {
            get {
                return ResourceManager.GetString("Frage_Formulieren_Textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KategorieName ähnelt.
        /// </summary>
        internal static string Frage_Kategorie_Vergeben {
            get {
                return ResourceManager.GetString("Frage_Kategorie_Vergeben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IstMultiSelect ähnelt.
        /// </summary>
        internal static string Frage_Mehrfachantwort_Vergeben {
            get {
                return ResourceManager.GetString("Frage_Mehrfachantwort_Vergeben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fragetext zu Frage 1 ähnelt.
        /// </summary>
        internal static string Frage_Musterfrage {
            get {
                return ResourceManager.GetString("Frage_Musterfrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fragebogen ähnelt.
        /// </summary>
        internal static string Fragebogen {
            get {
                return ResourceManager.GetString("Fragebogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RegSeite ähnelt.
        /// </summary>
        internal static string Fragen_Details {
            get {
                return ResourceManager.GetString("Fragen_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CatererBearbeitenSeite ähnelt.
        /// </summary>
        internal static string Fragen_Erstellen {
            get {
                return ResourceManager.GetString("Fragen_Erstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CatererBearbeitenSeite ähnelt.
        /// </summary>
        internal static string Fragen_Neu_Bearbeiten {
            get {
                return ResourceManager.GetString("Fragen_Neu_Bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CatererSeite ähnelt.
        /// </summary>
        internal static string Fragen_Übersicht_Neu {
            get {
                return ResourceManager.GetString("Fragen_Übersicht_Neu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CatererSeite ähnelt.
        /// </summary>
        internal static string Fragen_Übersicht_Öffentlich {
            get {
                return ResourceManager.GetString("Fragen_Übersicht_Öffentlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RegSeite ähnelt.
        /// </summary>
        internal static string Fragen_Veröffentlicht_Details {
            get {
                return ResourceManager.GetString("Fragen_Veröffentlicht_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die btnKategorieAnlegen ähnelt.
        /// </summary>
        internal static string Kategorie_Anlegen_Button {
            get {
                return ResourceManager.GetString("Kategorie_Anlegen_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CatererBearbeitenSeite ähnelt.
        /// </summary>
        internal static string Kategorie_Bearbeiten_Seite {
            get {
                return ResourceManager.GetString("Kategorie_Bearbeiten_Seite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Biobauer1 ähnelt.
        /// </summary>
        internal static string Kategorie_Dummykategorie {
            get {
                return ResourceManager.GetString("Kategorie_Dummykategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bezeichnung ähnelt.
        /// </summary>
        internal static string Kategorie_Formulieren_Textbox {
            get {
                return ResourceManager.GetString("Kategorie_Formulieren_Textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CatererBearbeitenSeite ähnelt.
        /// </summary>
        internal static string Kategorie_hinzufügen_Seite {
            get {
                return ResourceManager.GetString("Kategorie_hinzufügen_Seite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bezeichnung-error ähnelt.
        /// </summary>
        internal static string Kategorie_hinzufügen_Seite_Fehlermeldung {
            get {
                return ResourceManager.GetString("Kategorie_hinzufügen_Seite_Fehlermeldung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die btnFrageErstellen ähnelt.
        /// </summary>
        internal static string Kategorie_Neu_Button {
            get {
                return ResourceManager.GetString("Kategorie_Neu_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CatererSeite ähnelt.
        /// </summary>
        internal static string Kategorie_Übersicht_Seite {
            get {
                return ResourceManager.GetString("Kategorie_Übersicht_Seite", resourceCulture);
            }
        }
    }
}
