//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumTests.Services {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ObjektIDs_DatenManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjektIDs_DatenManagement() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumTests.Services.ObjektIDs_DatenManagement", typeof(ObjektIDs_DatenManagement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die btnEdit ähnelt.
        /// </summary>
        internal static string Daten_Bearbeiten {
            get {
                return ResourceManager.GetString("Daten_Bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RegSeite ähnelt.
        /// </summary>
        internal static string Eigene_Daten_Seite_Caterer {
            get {
                return ResourceManager.GetString("Eigene_Daten_Seite_Caterer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MitarbeiterBearbeitenSeite ähnelt.
        /// </summary>
        internal static string Eigene_Daten_Seite_Mitarbeiter {
            get {
                return ResourceManager.GetString("Eigene_Daten_Seite_Mitarbeiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die btnModalCancel ähnelt.
        /// </summary>
        internal static string Löschen_Abbrechen {
            get {
                return ResourceManager.GetString("Löschen_Abbrechen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LöschenButton ähnelt.
        /// </summary>
        internal static string Löschen_Button {
            get {
                return ResourceManager.GetString("Löschen_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die btnModalDelete ähnelt.
        /// </summary>
        internal static string Löschen_Ja {
            get {
                return ResourceManager.GetString("Löschen_Ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LöschenCancel ähnelt.
        /// </summary>
        internal static string Löschen_Nein {
            get {
                return ResourceManager.GetString("Löschen_Nein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LöschenBest ähnelt.
        /// </summary>
        internal static string Löschen_Seite {
            get {
                return ResourceManager.GetString("Löschen_Seite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die btnMarkierungenErstellen ähnelt.
        /// </summary>
        internal static string Mitarbeiter_Anlegen_Button {
            get {
                return ResourceManager.GetString("Mitarbeiter_Anlegen_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MitarbeiterBearbeitenSeite ähnelt.
        /// </summary>
        internal static string Mitarbeiter_Bearbeiten {
            get {
                return ResourceManager.GetString("Mitarbeiter_Bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RegSeite ähnelt.
        /// </summary>
        internal static string Mitarbeiter_Details {
            get {
                return ResourceManager.GetString("Mitarbeiter_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RegSeite ähnelt.
        /// </summary>
        internal static string Mitarbeiter_Hinzufügen {
            get {
                return ResourceManager.GetString("Mitarbeiter_Hinzufügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MitarbeiterSeite ähnelt.
        /// </summary>
        internal static string Mitarbeiter_Seite {
            get {
                return ResourceManager.GetString("Mitarbeiter_Seite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die btnSpeichern ähnelt.
        /// </summary>
        internal static string Speichern {
            get {
                return ResourceManager.GetString("Speichern", resourceCulture);
            }
        }
    }
}
